export const ErrorCodes = {
  // Authentication (AUTH_xxx)
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',

  // Authorization (AUTHZ_xxx)
  AUTHZ_PROJECT_ACCESS_DENIED: 'AUTHZ_PROJECT_ACCESS_DENIED',
  AUTHZ_RESOURCE_ACCESS_DENIED: 'AUTHZ_RESOURCE_ACCESS_DENIED',

  // Validation (VAL_xxx)
  VAL_REQUIRED_FIELD: 'VAL_REQUIRED_FIELD',
  VAL_INVALID_FORMAT: 'VAL_INVALID_FORMAT',
  VAL_STRING_TOO_LONG: 'VAL_STRING_TOO_LONG',
  VAL_INVALID_ENUM: 'VAL_INVALID_ENUM',
  VAL_INVALID_UUID: 'VAL_INVALID_UUID',

  // Resource (RES_xxx)
  RES_NOT_FOUND: 'RES_NOT_FOUND',
  RES_ALREADY_EXISTS: 'RES_ALREADY_EXISTS',
  RES_DELETED: 'RES_DELETED',
  RES_CONFLICT: 'RES_CONFLICT',

  // API Keys (KEY_xxx)
  KEY_NOT_CONFIGURED: 'KEY_NOT_CONFIGURED',
  KEY_INVALID: 'KEY_INVALID',
  KEY_EXPIRED: 'KEY_EXPIRED',
  KEY_RATE_LIMITED: 'KEY_RATE_LIMITED',
  KEY_QUOTA_EXCEEDED: 'KEY_QUOTA_EXCEEDED',
  KEY_DECRYPTION_FAILED: 'KEY_DECRYPTION_FAILED',

  // Image Generation (GEN_xxx)
  GEN_PROMPT_TOO_LONG: 'GEN_PROMPT_TOO_LONG',
  GEN_PROVIDER_ERROR: 'GEN_PROVIDER_ERROR',
  GEN_PROVIDER_TIMEOUT: 'GEN_PROVIDER_TIMEOUT',
  GEN_CONTENT_FILTERED: 'GEN_CONTENT_FILTERED',
  GEN_ALREADY_IN_PROGRESS: 'GEN_ALREADY_IN_PROGRESS',
  GEN_NO_PREVIOUS_IMAGE: 'GEN_NO_PREVIOUS_IMAGE',

  // Upload (UPL_xxx)
  UPL_FILE_TOO_LARGE: 'UPL_FILE_TOO_LARGE',
  UPL_INVALID_FILE_TYPE: 'UPL_INVALID_FILE_TYPE',
  UPL_S3_ERROR: 'UPL_S3_ERROR',

  // System (SYS_xxx)
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_DATABASE_ERROR: 'SYS_DATABASE_ERROR',
  SYS_SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
